import pandas as pd
import matplotlib.pyplot as plt

# Load your data from the file generated by your stats script
data = pd.read_csv('simulation_results.csv')

# Create the plot
plt.figure(figsize=(8, 6))

# Use a semi-log plot (standard for Bit Error Rate curves)
plt.semilogy(data['SNR_dB'], data['BER'], marker='o', linestyle='-', color='b', linewidth=2)

# Add labels and professional formatting
plt.title('PGDBF Decoder Performance (WiMAX 5/6 Rate)', fontsize=14)
plt.xlabel('Eb/N0 (dB)', fontsize=12)
plt.ylabel('Bit Error Rate (BER)', fontsize=12)
plt.grid(True, which="both", ls="--", alpha=0.7)

# Save and show
plt.savefig('ber_curve.png')
print("Graph saved as 'ber_curve.png'")
plt.show()